server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /auth

spring:
  application:
    name: cloud-auth
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres?currentSchema=cloud_auth
    username: postgres
    password: ${DB_PASSWORD:123456}
  flyway:
    schemas: cloud_auth
jwt:
  key-value: ${JWT_KEY_VALUE:neutar}


