server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /auth
clients:
  clientList:
    -
      clientId: "tecrubesi-ui"
      clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
      redirectUris: "${REDIRECT_URI:http://192.168.0.9:8082/login/oauth2/code/}"
users:
  -
    username: "utkan"
    password: ${PASSWORD:123456}


