version: '3.2'
services:
  cloud-auth:
    image: "cloud-auth:latest"
    ports:
      - "8090:8090"
    environment:
      - "DB_HOST=postgres_db"
      - "KAFKA_HOST=kafka"
      - "SERVER_PORT=8090"